// File generated from our OpenAPI spec by Stainless.

package com.court_listener_sdk.api.models.dockets

import com.court_listener_sdk.api.core.JsonValue
import com.court_listener_sdk.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class DocketTest {

    @Test
    fun create() {
        val docket =
            Docket.builder()
                .id(0L)
                .absoluteUrl("absolute_url")
                .appealFrom("https://example.com")
                .appealFromStr("appeal_from_str")
                .appellateCaseTypeInformation("appellate_case_type_information")
                .appellateFeeStatus("appellate_fee_status")
                .assignedTo("https://example.com")
                .assignedToStr("assigned_to_str")
                .addAudioFile("https://example.com")
                .bankruptcyInformation(
                    Docket.BankruptcyInformation.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .blocked(true)
                .caseName("case_name")
                .caseNameFull("case_name_full")
                .caseNameShort("case_name_short")
                .cause("cause")
                .addCluster("https://example.com")
                .court("https://example.com")
                .courtId("court_id")
                .dateArgued(LocalDate.parse("2019-12-27"))
                .dateBlocked(LocalDate.parse("2019-12-27"))
                .dateCertDenied(LocalDate.parse("2019-12-27"))
                .dateCertGranted(LocalDate.parse("2019-12-27"))
                .dateCreated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .dateFiled(LocalDate.parse("2019-12-27"))
                .dateLastFiling(LocalDate.parse("2019-12-27"))
                .dateLastIndex(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .dateModified(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .dateReargued(LocalDate.parse("2019-12-27"))
                .dateReargumentDenied(LocalDate.parse("2019-12-27"))
                .dateTerminated(LocalDate.parse("2019-12-27"))
                .docketNumber("docket_number")
                .docketNumberCore("docket_number_core")
                .filepathIa("https://example.com")
                .filepathIaJson("https://example.com")
                .iaDateFirstChange(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .iaNeedsUpload(true)
                .iaUploadFailureCount(0L)
                .idbData(
                    Docket.IdbData.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .jurisdictionType("jurisdiction_type")
                .juryDemand("jury_demand")
                .mdlStatus("mdl_status")
                .natureOfSuit("nature_of_suit")
                .originalCourtInfo(
                    Docket.OriginalCourtInfo.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .pacerCaseId("pacer_case_id")
                .addPanel("https://example.com")
                .panelStr("panel_str")
                .referredTo("https://example.com")
                .referredToStr("referred_to_str")
                .resourceUri("https://example.com")
                .slug("slug")
                .source(0L)
                .addTag("https://example.com")
                .build()

        assertThat(docket.id()).isEqualTo(0L)
        assertThat(docket.absoluteUrl()).isEqualTo("absolute_url")
        assertThat(docket.appealFrom()).isEqualTo("https://example.com")
        assertThat(docket.appealFromStr()).isEqualTo("appeal_from_str")
        assertThat(docket.appellateCaseTypeInformation())
            .isEqualTo("appellate_case_type_information")
        assertThat(docket.appellateFeeStatus()).isEqualTo("appellate_fee_status")
        assertThat(docket.assignedTo()).isEqualTo("https://example.com")
        assertThat(docket.assignedToStr()).isEqualTo("assigned_to_str")
        assertThat(docket.audioFiles()).containsExactly("https://example.com")
        assertThat(docket.bankruptcyInformation())
            .isEqualTo(
                Docket.BankruptcyInformation.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(docket.blocked()).isEqualTo(true)
        assertThat(docket.caseName()).isEqualTo("case_name")
        assertThat(docket.caseNameFull()).isEqualTo("case_name_full")
        assertThat(docket.caseNameShort()).isEqualTo("case_name_short")
        assertThat(docket.cause()).isEqualTo("cause")
        assertThat(docket.clusters()).containsExactly("https://example.com")
        assertThat(docket.court()).isEqualTo("https://example.com")
        assertThat(docket.courtId()).isEqualTo("court_id")
        assertThat(docket.dateArgued()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(docket.dateBlocked()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(docket.dateCertDenied()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(docket.dateCertGranted()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(docket.dateCreated()).isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(docket.dateFiled()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(docket.dateLastFiling()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(docket.dateLastIndex())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(docket.dateModified())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(docket.dateReargued()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(docket.dateReargumentDenied()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(docket.dateTerminated()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(docket.docketNumber()).isEqualTo("docket_number")
        assertThat(docket.docketNumberCore()).isEqualTo("docket_number_core")
        assertThat(docket.filepathIa()).isEqualTo("https://example.com")
        assertThat(docket.filepathIaJson()).isEqualTo("https://example.com")
        assertThat(docket.iaDateFirstChange())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(docket.iaNeedsUpload()).isEqualTo(true)
        assertThat(docket.iaUploadFailureCount()).isEqualTo(0L)
        assertThat(docket.idbData())
            .isEqualTo(
                Docket.IdbData.builder().putAdditionalProperty("foo", JsonValue.from("bar")).build()
            )
        assertThat(docket.jurisdictionType()).isEqualTo("jurisdiction_type")
        assertThat(docket.juryDemand()).isEqualTo("jury_demand")
        assertThat(docket.mdlStatus()).isEqualTo("mdl_status")
        assertThat(docket.natureOfSuit()).isEqualTo("nature_of_suit")
        assertThat(docket.originalCourtInfo())
            .isEqualTo(
                Docket.OriginalCourtInfo.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(docket.pacerCaseId()).isEqualTo("pacer_case_id")
        assertThat(docket.panel()).containsExactly("https://example.com")
        assertThat(docket.panelStr()).isEqualTo("panel_str")
        assertThat(docket.referredTo()).isEqualTo("https://example.com")
        assertThat(docket.referredToStr()).isEqualTo("referred_to_str")
        assertThat(docket.resourceUri()).isEqualTo("https://example.com")
        assertThat(docket.slug()).isEqualTo("slug")
        assertThat(docket.source()).isEqualTo(0L)
        assertThat(docket.tags()).containsExactly("https://example.com")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val docket =
            Docket.builder()
                .id(0L)
                .absoluteUrl("absolute_url")
                .appealFrom("https://example.com")
                .appealFromStr("appeal_from_str")
                .appellateCaseTypeInformation("appellate_case_type_information")
                .appellateFeeStatus("appellate_fee_status")
                .assignedTo("https://example.com")
                .assignedToStr("assigned_to_str")
                .addAudioFile("https://example.com")
                .bankruptcyInformation(
                    Docket.BankruptcyInformation.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .blocked(true)
                .caseName("case_name")
                .caseNameFull("case_name_full")
                .caseNameShort("case_name_short")
                .cause("cause")
                .addCluster("https://example.com")
                .court("https://example.com")
                .courtId("court_id")
                .dateArgued(LocalDate.parse("2019-12-27"))
                .dateBlocked(LocalDate.parse("2019-12-27"))
                .dateCertDenied(LocalDate.parse("2019-12-27"))
                .dateCertGranted(LocalDate.parse("2019-12-27"))
                .dateCreated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .dateFiled(LocalDate.parse("2019-12-27"))
                .dateLastFiling(LocalDate.parse("2019-12-27"))
                .dateLastIndex(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .dateModified(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .dateReargued(LocalDate.parse("2019-12-27"))
                .dateReargumentDenied(LocalDate.parse("2019-12-27"))
                .dateTerminated(LocalDate.parse("2019-12-27"))
                .docketNumber("docket_number")
                .docketNumberCore("docket_number_core")
                .filepathIa("https://example.com")
                .filepathIaJson("https://example.com")
                .iaDateFirstChange(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .iaNeedsUpload(true)
                .iaUploadFailureCount(0L)
                .idbData(
                    Docket.IdbData.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .jurisdictionType("jurisdiction_type")
                .juryDemand("jury_demand")
                .mdlStatus("mdl_status")
                .natureOfSuit("nature_of_suit")
                .originalCourtInfo(
                    Docket.OriginalCourtInfo.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .pacerCaseId("pacer_case_id")
                .addPanel("https://example.com")
                .panelStr("panel_str")
                .referredTo("https://example.com")
                .referredToStr("referred_to_str")
                .resourceUri("https://example.com")
                .slug("slug")
                .source(0L)
                .addTag("https://example.com")
                .build()

        val roundtrippedDocket =
            jsonMapper.readValue(jsonMapper.writeValueAsString(docket), jacksonTypeRef<Docket>())

        assertThat(roundtrippedDocket).isEqualTo(docket)
    }
}
