// File generated from our OpenAPI spec by Stainless.

package com.court_listener_sdk.api.models.dockets

import com.court_listener_sdk.api.core.JsonValue
import com.court_listener_sdk.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class DocketListPageResponseTest {

    @Test
    fun create() {
        val docketListPageResponse =
            DocketListPageResponse.builder()
                .count("count")
                .next("https://example.com")
                .previous("https://example.com")
                .addResult(
                    Docket.builder()
                        .id(0L)
                        .absoluteUrl("absolute_url")
                        .appealFrom("https://example.com")
                        .appealFromStr("appeal_from_str")
                        .appellateCaseTypeInformation("appellate_case_type_information")
                        .appellateFeeStatus("appellate_fee_status")
                        .assignedTo("https://example.com")
                        .assignedToStr("assigned_to_str")
                        .addAudioFile("https://example.com")
                        .bankruptcyInformation(
                            Docket.BankruptcyInformation.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .blocked(true)
                        .caseName("case_name")
                        .caseNameFull("case_name_full")
                        .caseNameShort("case_name_short")
                        .cause("cause")
                        .addCluster("https://example.com")
                        .court("https://example.com")
                        .courtId("court_id")
                        .dateArgued(LocalDate.parse("2019-12-27"))
                        .dateBlocked(LocalDate.parse("2019-12-27"))
                        .dateCertDenied(LocalDate.parse("2019-12-27"))
                        .dateCertGranted(LocalDate.parse("2019-12-27"))
                        .dateCreated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateFiled(LocalDate.parse("2019-12-27"))
                        .dateLastFiling(LocalDate.parse("2019-12-27"))
                        .dateLastIndex(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateModified(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateReargued(LocalDate.parse("2019-12-27"))
                        .dateReargumentDenied(LocalDate.parse("2019-12-27"))
                        .dateTerminated(LocalDate.parse("2019-12-27"))
                        .docketNumber("docket_number")
                        .docketNumberCore("docket_number_core")
                        .filepathIa("https://example.com")
                        .filepathIaJson("https://example.com")
                        .iaDateFirstChange(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .iaNeedsUpload(true)
                        .iaUploadFailureCount(0L)
                        .idbData(
                            Docket.IdbData.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .jurisdictionType("jurisdiction_type")
                        .juryDemand("jury_demand")
                        .mdlStatus("mdl_status")
                        .natureOfSuit("nature_of_suit")
                        .originalCourtInfo(
                            Docket.OriginalCourtInfo.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .pacerCaseId("pacer_case_id")
                        .addPanel("https://example.com")
                        .panelStr("panel_str")
                        .referredTo("https://example.com")
                        .referredToStr("referred_to_str")
                        .resourceUri("https://example.com")
                        .slug("slug")
                        .source(0L)
                        .addTag("https://example.com")
                        .build()
                )
                .build()

        assertThat(docketListPageResponse.count()).isEqualTo("count")
        assertThat(docketListPageResponse.next()).isEqualTo("https://example.com")
        assertThat(docketListPageResponse.previous()).isEqualTo("https://example.com")
        assertThat(docketListPageResponse.results())
            .containsExactly(
                Docket.builder()
                    .id(0L)
                    .absoluteUrl("absolute_url")
                    .appealFrom("https://example.com")
                    .appealFromStr("appeal_from_str")
                    .appellateCaseTypeInformation("appellate_case_type_information")
                    .appellateFeeStatus("appellate_fee_status")
                    .assignedTo("https://example.com")
                    .assignedToStr("assigned_to_str")
                    .addAudioFile("https://example.com")
                    .bankruptcyInformation(
                        Docket.BankruptcyInformation.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .blocked(true)
                    .caseName("case_name")
                    .caseNameFull("case_name_full")
                    .caseNameShort("case_name_short")
                    .cause("cause")
                    .addCluster("https://example.com")
                    .court("https://example.com")
                    .courtId("court_id")
                    .dateArgued(LocalDate.parse("2019-12-27"))
                    .dateBlocked(LocalDate.parse("2019-12-27"))
                    .dateCertDenied(LocalDate.parse("2019-12-27"))
                    .dateCertGranted(LocalDate.parse("2019-12-27"))
                    .dateCreated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateFiled(LocalDate.parse("2019-12-27"))
                    .dateLastFiling(LocalDate.parse("2019-12-27"))
                    .dateLastIndex(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateModified(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateReargued(LocalDate.parse("2019-12-27"))
                    .dateReargumentDenied(LocalDate.parse("2019-12-27"))
                    .dateTerminated(LocalDate.parse("2019-12-27"))
                    .docketNumber("docket_number")
                    .docketNumberCore("docket_number_core")
                    .filepathIa("https://example.com")
                    .filepathIaJson("https://example.com")
                    .iaDateFirstChange(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .iaNeedsUpload(true)
                    .iaUploadFailureCount(0L)
                    .idbData(
                        Docket.IdbData.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .jurisdictionType("jurisdiction_type")
                    .juryDemand("jury_demand")
                    .mdlStatus("mdl_status")
                    .natureOfSuit("nature_of_suit")
                    .originalCourtInfo(
                        Docket.OriginalCourtInfo.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .pacerCaseId("pacer_case_id")
                    .addPanel("https://example.com")
                    .panelStr("panel_str")
                    .referredTo("https://example.com")
                    .referredToStr("referred_to_str")
                    .resourceUri("https://example.com")
                    .slug("slug")
                    .source(0L)
                    .addTag("https://example.com")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val docketListPageResponse =
            DocketListPageResponse.builder()
                .count("count")
                .next("https://example.com")
                .previous("https://example.com")
                .addResult(
                    Docket.builder()
                        .id(0L)
                        .absoluteUrl("absolute_url")
                        .appealFrom("https://example.com")
                        .appealFromStr("appeal_from_str")
                        .appellateCaseTypeInformation("appellate_case_type_information")
                        .appellateFeeStatus("appellate_fee_status")
                        .assignedTo("https://example.com")
                        .assignedToStr("assigned_to_str")
                        .addAudioFile("https://example.com")
                        .bankruptcyInformation(
                            Docket.BankruptcyInformation.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .blocked(true)
                        .caseName("case_name")
                        .caseNameFull("case_name_full")
                        .caseNameShort("case_name_short")
                        .cause("cause")
                        .addCluster("https://example.com")
                        .court("https://example.com")
                        .courtId("court_id")
                        .dateArgued(LocalDate.parse("2019-12-27"))
                        .dateBlocked(LocalDate.parse("2019-12-27"))
                        .dateCertDenied(LocalDate.parse("2019-12-27"))
                        .dateCertGranted(LocalDate.parse("2019-12-27"))
                        .dateCreated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateFiled(LocalDate.parse("2019-12-27"))
                        .dateLastFiling(LocalDate.parse("2019-12-27"))
                        .dateLastIndex(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateModified(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateReargued(LocalDate.parse("2019-12-27"))
                        .dateReargumentDenied(LocalDate.parse("2019-12-27"))
                        .dateTerminated(LocalDate.parse("2019-12-27"))
                        .docketNumber("docket_number")
                        .docketNumberCore("docket_number_core")
                        .filepathIa("https://example.com")
                        .filepathIaJson("https://example.com")
                        .iaDateFirstChange(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .iaNeedsUpload(true)
                        .iaUploadFailureCount(0L)
                        .idbData(
                            Docket.IdbData.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .jurisdictionType("jurisdiction_type")
                        .juryDemand("jury_demand")
                        .mdlStatus("mdl_status")
                        .natureOfSuit("nature_of_suit")
                        .originalCourtInfo(
                            Docket.OriginalCourtInfo.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .pacerCaseId("pacer_case_id")
                        .addPanel("https://example.com")
                        .panelStr("panel_str")
                        .referredTo("https://example.com")
                        .referredToStr("referred_to_str")
                        .resourceUri("https://example.com")
                        .slug("slug")
                        .source(0L)
                        .addTag("https://example.com")
                        .build()
                )
                .build()

        val roundtrippedDocketListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(docketListPageResponse),
                jacksonTypeRef<DocketListPageResponse>(),
            )

        assertThat(roundtrippedDocketListPageResponse).isEqualTo(docketListPageResponse)
    }
}
